# Test MakeWithPerl 2023-02-03 at 05:11:47

name: Test

on:
  push

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Install Data::Table::Text
      run: |
        sudo cpan install -T Data::Table::Text Test::Most

    - name: Test
      run: |
        perl -Ilib test.pl

  mac:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Install Data::Table::Text
      run: |
        sudo cpan install -T Data::Table::Text Test::Most

    - name: Test
      run: |
        perl -Ilib test.pl
